### ISSUE TITLE
Modernize python packaging setup

### ISSUE THREAD

**Issue by swvanbuuren** [swvanbuuren/pqthreads#12]
The current approach still uses the old `setup.py` approach, which is outdated and not recommended anymore.

With this issue it's proposed to move the model approach using `pyproject.toml`. 

For starters, one could use the following `pyproject.toml`:

```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pqthreads"
version = "0.1"
description = "Expose class interfaces from the main GUI Thread in another QThread in Qt for Python"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Sietze van Buuren", email = "s.van.buuren@gmail.com" }
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",  # Add the correct license classifier
    "Operating System :: OS Independent",
]
urls = { Homepage = "https://github.com/swvanbuuren/pqthreads" }
dependencies = [
    "PySide6"
]

[tool.setuptools.packages.find]
include = ["pqthreads", "pqthreads.*"]
```
